.PHONY: build clean deploy gomodgen

build: gomodgen
	export GO111MODULE=on
	env GOOS=linux go build -ldflags="-s -w" -o bin/helloworld helloworld/main.go

clean:
	rm -rf ./bin ./vendor Gopkg.lock

deploy: clean build
	sls deploy --verbose

invoke:
	sls invoke -f helloworld

invoke-local: build
	sls invoke local -f helloworld

gomodgen:
	chmod u+x gomod.sh
	./gomod.sh
