service: helloworld
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-northeast-1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  helloworld:
    handler: bin/helloworld
    events:
      - http:
          path: helloworld
          method: get
